spring:
  application:
    name: employee-service
  config:
    import: optional:.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
server:
  port: 0

mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml
  mapper-locations: classpath:db/mybatis/mapper/*.xml
  type-aliases-package: com.gznznzjsn.employeeservice.domain

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL}
  instance:
    prefer-ip-address: true
